name: cppcheck
on: 
  workflow_call:

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          std: c11
          other_options: --error-exitcode=69
      - name: Print cppcheck_report.txt
        if: always()
        run: cat cppcheck_report.txt